name: Build and push docker image

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  push_to_registry:
    environment: docker_build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/fhcrc/deenurp:latest
            ghcr.io/fhcrc/deenurp:${{ env.RELEASE_VERSION }}
