name: Run deenurp tests on deenurp image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fhcrc/deenurp:latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        python3 -m deenurp.test
        tests/run.sh
