---
name: Run tests and deploy tag to registry

on:
  push:
    branches:
      - "*"
    tags: 
      - "v*.*.*"
  pull_request:
    branches:
      - $default-branch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: ${{ steps.meta.outputs.labels }}
        load: true
        push: false
        tags: |
          ${{ steps.meta.outputs.tags }}
          gha_image

    - name: Run tests
      run: docker run gha_image /bin/bash -c "cd /usr/local/share/deenurp/;python3 -m deenurp.test;tests/run.sh"

    - name: Push tag to ${{ env.REGISTRY }}
      if: github.ref_type == 'tag'
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
