name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: crosenth/deenurp:v0.3.0

    steps:
    - name: Tests
      run: python3 -m deenurp.test
      run: tests/run.sh
