name: Run tests

on:
  push:
    branches: [ gh_actions ]
  pull_request:
    branches: [ master ]

env:
  VIRTUAL_ENV: $HOME/.local

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: provisioning
      run: bin/bootstrap.sh $VIRTUAL_ENV
      # - name: testing
      # - run: python3 -m deenurp.test
